---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1808991/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index_backup.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp service.html $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R files $DEPLOYPATH
  